# Generated by Django 2.0.5 on 2019-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdd_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('records', models.CharField(max_length=1000)),
                ('organizationtype', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=100)),
                ('adddata', models.CharField(max_length=500)),
                ('attackresult', models.CharField(max_length=500)),
                ('time', models.TimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='useradd_model',
            name='uregid',
            field=models.ForeignKey(on_delete='cascade', to='Cyber_Users.UserRegister_Model'),
        ),
    ]
