# Generated by Django 2.0.5 on 2019-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd_model',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
